name: Create Release

on:
  workflow_run:
    workflows: ['Test Bash Script']
    types:
      - completed

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: 'Determine tag'
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Upload release asset'
        uses: 'xresloader/upload-to-github-release@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'install.sh'
          tags: true
          draft: false
          tag_name: ${{ env.RELEASE_TAG }}
