name: Create Release

on:
  workflow_run:
    workflows: ['Test Bash Script']
    types:
      - completed

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Changelog
        id: changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 'Release ${{ github.ref.tag }} 📢'
          body: |
            ## Changelog

            ${{ steps.changelog.outputs.changelog }}

            ## Installation

            ### Linux

            ```bash
            curl -sSL https://raw.githubusercontent.com/PunGrumpy/dotfiles-installer/main/install.sh | bash
            ```
            ---
            Thank you for downloading and using dotfiles installer! 🎉
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'install.sh'
          tags: true
          draft: false
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
