name: Create Release

on:
  workflow_run:
    workflows: ['Test Bash Script']
    types:
      - completed

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Changelog
        id: changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create Tag
        id: create_tag
        run: |
          git tag -a "release-${GITHUB_RUN_NUMBER}" -m "Release ${{ github.run_number }}"
          git push origin "release-${GITHUB_RUN_NUMBER}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: 'Release ${{ steps.create_tag.outputs.tag_name }} 📢'
          body: |
            ## Changelog

            ${{ steps.changelog.outputs.changelog }}

            ## Installation

            ### Linux

            ```bash
            curl -sSL https://raw.githubusercontent.com/PunGrumpy/dotfiles-installer/main/install.sh | bash
            ```
            ---
            Thank you for downloading and using dotfiles installer! 🎉
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'install.sh'
          tags: true
          draft: false
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
